# MLflow Configuration for Travel Advisor Chatbot
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "travel_chatbot"
  registry_uri: "file:./mlruns"
  
experiments:
  rag_model:
    name: "rag_model_experiment"
    description: "RAG model training experiments"
    
  embedding_model:
    name: "embedding_model_experiment"
    description: "Word embedding model experiments"
    
  llm_model:
    name: "llm_model_experiment"
    description: "LLM integration experiments"
    
  few_shot_model:
    name: "few_shot_model_experiment"
    description: "Few-shot learning experiments"

model_registry:
  name: "travel_chatbot_models"
  description: "Travel Advisor Chatbot Model Registry"
  
artifacts:
  model_path: "./models"
  data_path: "./data"
  logs_path: "./logs"
  
tracking:
  log_models: true
  log_artifacts: true
  log_parameters: true
  log_metrics: true
